_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 76
                - 77
            "3":
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
batch_size:
    value: 128
dataset:
    value: ogbg-molhiv
epochs:
    value: 2
gpu:
    value: 0
learning_rate:
    value: 0.005
load_path:
    value: saved/moco/current.pth
model_path:
    value: ./checkpoints
num_workers:
    value: 4
weight_decay:
    value: 1e-05
